# -*- coding: utf-8 -*-
"""FakeNewsDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1devttGsOx6KMDdLcOROAu0hK006NLVPR

# Pendeteksian Berita Palsu dengan Python

Selasa, 21 Desember 2021

Muhamad Abdul Karim

Sumber: [Data-Flair](https://data-flair.training/)
"""

import numpy as np
import pandas as pd
import itertools
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

#Membaca data
dataframenya = pd.read_csv("news.csv")

#menampilkan shape dan lima baris pertama dalam dataset
print("shape : ", dataframenya.shape)
dataframenya.head()

#Menampilkan label-labelnya
labels = dataframenya.label
labels.head()

#Split dataset menjadi training dan testing sets
x_train, x_test, y_train, y_test = train_test_split(dataframenya['text'], labels, test_size=0.2, random_state=7)

#Inisialisasi TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)

#Fit dan transform train set, transform test set
tfidf_train = tfidf_vectorizer.fit_transform(x_train) 
tfidf_test = tfidf_vectorizer.transform(x_test)

#Inisialisasi PassiveAggressiveClassifier
pac = PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train, y_train)

#Prediksi test set dan kalkulasi keakuratan
y_pred = pac.predict(tfidf_test)
score = accuracy_score(y_test, y_pred)
print(f'Akurasi : {round(score*100,2)}%')

#Membuat confusion matrix
confusion_matrix(y_test,y_pred, labels = ['FAKE','REAL'])